"""Curated deep-profile drug set for the drug-intelligence database.

These drugs get the FULL depth (US/CN marketed products, patents/exclusivity,
DrugBank pKa/logS, CN 参比制剂) — as opposed to the ~4,225 catalog drugs which
carry a lightweight identity+physicochemical profile only.

Chosen to be common and formulation-relevant, spanning therapeutic classes and
BCS classes (weak acids/bases, high/low solubility, salts, poorly-soluble
solid-dispersion candidates). Add names here and re-run
``scripts/build_drug_intelligence.py`` (+ import_cn_reference_drugfuture.py),
then ``scripts/prebuild_catalog_lite.py``.
"""

CURATED_DRUGS = [
    # ── NSAIDs / analgesics ──────────────────────────────────────────────
    "Ibuprofen", "Aspirin", "Naproxen", "Diclofenac", "Celecoxib",
    "Ketoprofen", "Indomethacin", "Meloxicam", "Piroxicam", "Etoricoxib",
    "Paracetamol", "Tramadol", "Morphine", "Codeine",
    # ── Cardiovascular / lipid / antithrombotic ──────────────────────────
    "Atorvastatin", "Simvastatin", "Rosuvastatin", "Pravastatin",
    "Amlodipine", "Nifedipine", "Diltiazem", "Verapamil",
    "Lisinopril", "Enalapril", "Valsartan", "Losartan", "Candesartan",
    "Metoprolol", "Bisoprolol", "Carvedilol", "Propranolol",
    "Clopidogrel", "Ticagrelor", "Warfarin", "Rivaroxaban", "Apixaban",
    "Furosemide", "Hydrochlorothiazide", "Spironolactone", "Digoxin",
    # ── Antidiabetics ────────────────────────────────────────────────────
    "Metformin", "Glibenclamide", "Gliclazide", "Glimepiride",
    "Empagliflozin", "Dapagliflozin", "Sitagliptin", "Pioglitazone",
    # ── CNS / psychiatry / neurology ─────────────────────────────────────
    "Sertraline", "Fluoxetine", "Paroxetine", "Escitalopram",
    "Venlafaxine", "Duloxetine", "Diazepam", "Alprazolam",
    "Quetiapine", "Olanzapine", "Risperidone", "Aripiprazole",
    "Gabapentin", "Pregabalin", "Levetiracetam", "Lamotrigine",
    "Carbamazepine", "Valproate", "Donepezil",
    # ── GI ───────────────────────────────────────────────────────────────
    "Omeprazole", "Esomeprazole", "Lansoprazole", "Pantoprazole",
    "Ranitidine", "Ondansetron",
    # ── Anti-infectives / antifungals / antivirals ───────────────────────
    "Amoxicillin", "Azithromycin", "Clarithromycin", "Ciprofloxacin",
    "Levofloxacin", "Doxycycline", "Metronidazole",
    "Fluconazole", "Itraconazole", "Voriconazole", "Griseofulvin",
    "Acyclovir", "Oseltamivir",
    # ── Respiratory / allergy ────────────────────────────────────────────
    "Montelukast", "Salbutamol", "Budesonide", "Cetirizine", "Loratadine",
    # ── Oncology / endocrine ─────────────────────────────────────────────
    "Imatinib", "Gefitinib", "Erlotinib", "Sorafenib",
    "Methotrexate", "Tamoxifen", "Letrozole", "Anastrozole", "Capecitabine",
    # ── Poorly-soluble / other formulation-interesting ───────────────────
    "Fenofibrate", "Sildenafil", "Tadalafil", "Ketoconazole",
    "Allopurinol", "Febuxostat", "Prednisolone", "Dexamethasone",
    "Levothyroxine", "Tamsulosin", "Finasteride",

    # ── expansion wave 2 (~390): common drugs for dataset scale-up ──────
    # NSAIDs / analgesic / anesthetic
    "Sulindac", "Tolmetin", "Meclofenamate", "Mefenamic acid", "Nabumetone",
    "Oxaprozin", "Tiaprofenic acid", "Flurbiprofen", "Ketorolac", "Licofelone",
    "Acetaminophen", "Propacetamol", "Nefopam", "Flupirtine",
    "Celecoxib", "Parecoxib", "Valdecoxib", "Lornoxicam", "Tenoxicam",
    "Ibuprofen lysinate", "Naproxen sodium", "Diclofenac sodium",
    # antibiotics / antimicrobials
    "Penicillin V", "Amoxicillin-clavulanate", "Flucloxacillin", "Dicloxacillin",
    "Cephalexin", "Cefuroxime", "Cefixime", "Cefpodoxime", "Cefdinir",
    "Ceftriaxone", "Ceftazidime", "Cefepime", "Cefazolin",
    "Clindamycin", "Linezolid", "Vancomycin", "Teicoplanin", "Daptomycin",
    "Gentamicin", "Amikacin", "Tobramycin", "Erythromycin", "Roxithromycin",
    "Spiramycin", "Telithromycin", "Fosfomycin", "Nitrofurantoin",
    "Trimethoprim-sulfamethoxazole", "Moxifloxacin", "Gemifloxacin",
    "Trovafloxacin", "Tigecycline", "Colistin", "Polymyxin B",
    "Isoniazid", "Rifampicin", "Pyrazinamide", "Ethambutol",
    "Ketoconazole", "Clotrimazole", "Miconazole", "Amphotericin B",
    "Valacyclovir", "Famciclovir", "Ganciclovir", "Valganciclovir",
    "Lamivudine", "Zidovudine", "Tenofovir", "Entecavir", "Adefovir",
    "Telbivudine", "Sofosbuvir", "Ledipasvir", "Daclatasvir", "Ribavirin",
    "Oseltamivir phosphate", "Zanamivir", "Baloxavir", "Favipiravir",
    "Hydroxychloroquine", "Chloroquine", "Artemisinin", "Artemether",
    "Lumefantrine", "Primaquine", "Quinine", "Mefloquine", "Albendazole",
    "Mebendazole", "Praziquantel", "Ivermectin",
    # cardiovascular more
    "Felodipine", "Nicardipine", "Nisoldipine", "Lercanidipine", "Benidipine",
    "Barnidipine", "Efonidipine", "Manidipine",
    "Irbesartan", "Olmesartan", "Telmisartan", "EXP3174", "Candesartan cilexetil",
    "Ramipril", "Perindopril", "Quinapril", "Fosinopril", "Trandolapril",
    "Benazepril", "Captopril", "Moexipril", "Spirapril",
    "Nebivolol", "Acebutolol", "Atenolol", "Betaxolol", "Bisoprolol",
    "Esmolol", "Sotalol", "Timolol", "Pindolol", "Labetalol",
    "Flecainide", "Propafenone", "Amiodarone", "Dronedarone", "Sotalol AF",
    "Ivabradine", "Ranolazine", "Trimetazidine", "Nicorandil",
    "Atorvastatin calcium", "Fluvastatin", "Pitavastatin", "Cerivastatin",
    "Ezetimibe", "Evolocumab".lower(), "Alirocumab".lower(),
    "Fenofibric acid", "Bezafibrate", "Ciprofibrate", "Gemfibrozil",
    "Nicotinic acid", "Acipimox", "Omega-3-acid ethyl esters",
    "Enoxaparin", "Dalteparin", "Fondaparinux", "Bivalirudin", "Argatroban",
    "Dabigatran", "Edoxaban", "Dipyridamole", "Cilostazol", "Beraprost",
    "Doxazosin", "Prazosin", "Terazosin", "Urapidil", "Moxonidine",
    "Hydralazine", "Minoxidil", "Nitroprusside", "Nitroglycerin",
    "Isosorbide dinitrate", "Isosorbide mononitrate", "Pentaerythritol tetranitrate",
    # diabetes / endocrine more
    "Repaglinide", "Nateglinide", "Acarbose", "Voglibose", "Miglitol",
    "Rosiglitazone", "Liraglutide", "Exenatide", "Sitagliptin phosphate",
    "Saxagliptin", "Alogliptin", "Linagliptin", "Vildagliptin",
    "Insulin glargine", "Insulin aspart", "Insulin lispro", "Insulin human",
    "Levothyroxine sodium", "Liothyronine", "Carbimazole", "Methimazole",
    "Propylthiouracil", "Cinacalcet", "Teriparatide", "Alendronate",
    "Risedronate", "Zoledronic acid", "Ibandronate", "Etidronate",
    "Calcitriol", "Cholecalciferol", "Ergocalciferol",
    # CNS more
    "Amitriptyline", "Nortriptyline", "Imipramine", "Clomipramine",
    "Mirtazapine", "Bupropion", "Trazodone", "Nefazodone", "Reboxetine",
    "Atomoxetine", "Methylphenidate", "Modafinil", "Armodafinil",
    "Risperidone", "Paliperidone", "Ziprasidone", "Clozapine",
    "Haloperidol", "Sulpiride", "Amisulpride", "Fluphenazine",
    "Lithium carbonate", "Valproic acid", "Topiramate", "Zonisamide",
    "Oxcarbazepine", "Eslicarbazepine", "Retigabine", "Brivaracetam",
    "Phenytoin", "Phenobarbital", "Primidone", "Ethosuximide", "Clonazepam",
    "Lorazepam", "Oxazepam", "Temazepam", "Midazolam", "Zolpidem",
    "Zopiclone", "Eszopiclone", "Zaleplon", "Buspirone",
    "Rivastigmine", "Galantamine", "Memantine", "Selegiline",
    "Rasagiline", "Levodopa", "Carbidopa", "Pramipexole", "Ropinirole",
    "Rotigotine", "Entacapone", "Tolcapone", "Amantadine",
    "Sumatriptan", "Rizatriptan", "Zolmitriptan", "Naratriptan",
    "Eletriptan", "Frovatriptan", "Almotriptan", "Ergotamine",
    "Flunarizine", "Cinnarizine",
    # GI / urinary more
    "Famotidine", "Nizatidine", "Roxatidine", "Cimetidine",
    "Sucralfate", "Misoprostol", "Itopride", "Mosapride", "Cisapride",
    "Domperidone", "Metoclopramide", "Tegaserod", "Linaclotide",
    "Loperamide", "Diphenoxylate", "Racecadotril", "Pinaverium",
    "Trimebutine", "Alverine", "Mebeverine", "Otilonium",
    "Ursodeoxycholic acid", "Obeticholic acid", "Silymarin",
    "Solifenacin", "Darifenacin", "Trospium", "Propiverine",
    # respiratory / allergy more
    "Formoterol", "Salmeterol", "Indacaterol", "Olodaterol", "Vilanterol",
    "Ipratropium", "Tiotropium", "Glycopyrronium", "Umeclidinium",
    "Aclidinium", "Revefenacin", "Theophylline", "Aminophylline",
    "Doxofylline", "Zafirlukast", "Pranlukast", "Zileuton",
    "Fexofenadine", "Desloratadine", "Levocetirizine", "Mizolastine",
    "Azatadine", "Bilastine", "Rupatadine", "Ebastine",
    "Beclomethasone", "Fluticasone", "Mometasone", "Ciclesonide",
    "Prednisone", "Methylprednisolone", "Triamcinolone", "Betamethasone",
    "Hydrocortisone", "Budesonide-formoterol",
    # oncology / immunology more
    "Sunitinib", "Sorafenib tosylate", "Regorafenib", "Lenvatinib",
    "Axitinib", "Pazopanib", "Cabozantinib", "Vandetanib",
    "Erlotinib hydrochloride", "Afatinib", "Osimertinib", "Icotinib",
    "Crizotinib", "Ceritinib", "Alectinib", "Brigatinib",
    "Dasatinib", "Nilotinib", "Bosutinib", "Ponatinib",
    "Ruxolitinib", "Tofacitinib", "Baricitinib", "Upadacitinib",
    "Vemurafenib", "Dabrafenib", "Trametinib", "Cobimetinib",
    "Palbociclib", "Ribociclib", "Abemaciclib",
    "Enzalutamide", "Abiraterone", "Apalutamide", "Bicalutamide",
    "Cyclophosphamide", "Ifosfamide", "Cisplatin", "Carboplatin",
    "Oxaliplatin", "Doxorubicin", "Epirubicin", "Daunorubicin",
    "Paclitaxel", "Docetaxel", "Vinblastine", "Vincristine",
    "Vinorelbine", "Etoposide", "Teniposide", "Irinotecan",
    "Topotecan hydrochloride", "Bleomycin", "Mitomycin", "Gemcitabine",
    "Azacitidine", "Decitabine", "Hydroxycarbamide", "Bortezomib",
    "Everolimus", "Sirolimus", "Tacrolimus", "Mycophenolate mofetil",
    "Azathioprine", "Ciclosporin", "Leflunomide", "Sulfasalazine",
    "Hydroxychloroquine sulfate", "Anakinra", "Tocilizumab",
    # others / misc formulation-relevant
    "Losartan potassium", "Valsartan-amlodipine", "Spironolactone",
    "Eplerenone", "Canrenone", "Amiloride", "Triamterene", "Acetazolamide",
    "Mannitol", "Tolvaptan", "Conivaptan",
    "Allopurinol", "Febuxostat", "Probenecid", "Sulfinpyrazone",
    "Lesinurad", "Pegloticase", "Rasburicase",
    "Tamsulosin hydrochloride", "Silodosin", "Naftopidil",
    "Sildenafil citrate", "Vardenafil", "Avanafil", "Apomorphine",
    "Alprostadil", "Papaverine",
    "Minoxidil topical", "Finasteride", "Dutasteride",
    "Tranexamic acid", "Aminocaproic acid", "Aprotinin",
    "Vitamin C", "Vitamin B1", "Vitamin B6", "Vitamin B12",
    "Folic acid", "Vitamin A", "Vitamin E", "Vitamin K1",
    "Calcium carbonate", "Ferrous sulfate", "Ferrous fumarate",
    "Iron sucrose", "Ferric carboxymaltose", "Erythropoietin",
    "N-acetylcysteine", "Ambroxol", "Bromhexine", "Erdosteine",
    "Carbocisteine", "Fudosteine", "Eprazinone",
    "Deferasirox", "Deferiprone", "Deferoxamine",
    "Pentoxifylline", "Cilostazol", "Naftidrofuryl",
    "Ginkgo biloba extract", "Donepezil hydrochloride",
]
